@startuml
class DeviceDriver {
    + init()
    + exit()
}

class Driver1 {
    + init()
    + exit()
}

class Driver2 {
    + init()
    + exit()
}

class DriverFactory {
    + create_driver(int type): DeviceDriver*
}

DeviceDriver <|.. Driver1
DeviceDriver <|.. Driver2
DriverFactory --> DeviceDriver

@enduml

@startuml
actor User
participant DriverFactory
participant DeviceDriver

User -> DriverFactory: create_driver(1)
DriverFactory -> DeviceDriver: 返回 Driver1 实例
User -> DeviceDriver: init()
@enduml